apiVersion: v1
kind: ConfigMap
metadata:
  name: ivy-config
data:
  LICENCE: |
    [Begin Licence]
    #Licence for AxonIvy Axon Ivy Engine (Enterprise Edition)
    #Thu Jul 03 11:43:58 CEST 2025
    licence.keyversion=axonivy/13000
    licence.number=XLSEE-197C-FABE-480C
    licence.type=Enterprise Edition
    licence.valid.until=2027-11-03
    licencee.individual=www.axonivy.com
    licencee.organisation=Axon Ivy AG
    product.name=Axon Ivy Engine
    public.urls=localhost,*.app.github.dev,raccoon.local
    server.nodes.limit=5
    server.sessions.limit=2
    server.users.limit=4
    [End Licence]
    [Begin Signature]
    MCwCFARlfvRkU3gpjodGPST63oPc7J0tAhQkMeLIzHEKh+8sknIet3wN0wNjIQ==
    [End Signature]

  LOG4J2: |
    <Configuration>
      <Appenders>
        <Console name="ConsoleLog" target="SYSTEM_OUT">
          <PatternLayout pattern="${pattern}" />
          <ThresholdFilter level="debug" />
        </Console>
      </Appenders>
      <Loggers>
        <Logger name="org.jgroups" level="debug"/>
        <Logger name="ch.ivyteam.ivy.cluster" level="debug"/>
      </Loggers>
    </Configuration>

  JGROUPS: |
    <config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd"
        >
    <TCP bind_addr="${jgroups.bind_addr:site_local}"
         bind_port="${jgroups.bind_port:7800}"
         thread_pool.min_threads="0"
         thread_pool.max_threads="200"
         thread_pool.keep_alive_time="30000"/>
    <RED/>
    <!-- dns_address="10.96.0.10" -->
    <dns.DNS_PING        
        dns_query="ivy.sandbox.svc.cluster.local"/>
    <MERGE3 max_interval="30s"
            min_interval="10s"/>
    <FD_SOCK2/>
    <FD_ALL3/>
    <VERIFY_SUSPECT2 timeout="1.5s"  />
    <BARRIER />
    <pbcast.NAKACK2 xmit_interval="0.5s"/>
    <UNICAST3 xmit_interval="0.5s" />
    <pbcast.STABLE desired_avg_gossip="50s"
                   max_bytes="4M"/>
    <pbcast.GMS print_local_addr="true" join_timeout="1s"/>
    <MFC max_credits="4M"
         min_threshold="0.4"/>
    <UFC max_credits="4M"
             min_threshold="0.4"/>
    <FRAG2 frag_size="60K"  />
    <pbcast.STATE_TRANSFER />
    </config>
